import test from "node:test";
import assert from "node:assert/strict";
import { qrCodeDataUri } from "../lib/authenticator-qr.js";

const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><path fill="black" d="M0 0h7v7H0z"/></svg>';
const decode = value => Buffer.from(value.split(",")[1], "base64").toString("utf8");

test("accepts the XML declaration and generated comment used by Supabase Auth", () => {
  const providerImage = `<?xml version="1.0"?>\n<!-- Generated by SVGo -->\n${svg}`;
  assert.equal(decode(qrCodeDataUri(providerImage)), svg);
  assert.equal(decode(qrCodeDataUri(`\uFEFF <?xml version="1.0" encoding="UTF-8"?>\n<!-- first -->\n<!-- second -->\n${svg}`)), svg);
});

test("preserves existing raw SVG and SVG data URI formats", () => {
  const encoded = qrCodeDataUri(svg);
  assert.equal(decode(encoded), svg);
  assert.equal(qrCodeDataUri(encoded), encoded);
  const uri = `data:image/svg+xml,${encodeURIComponent(svg)}`;
  assert.equal(qrCodeDataUri(uri), uri);
});

test("does not turn external URLs, HTML, other XML documents or oversized values into QR images", () => {
  for (const value of [null, {}, 123, "", "https://example.test/qr.svg", "javascript:alert(1)", "data:text/html,<svg/>", `<html>${svg}</html>`, `<?xml-stylesheet href="external.css"?>${svg}`, `<!DOCTYPE svg SYSTEM "external">${svg}`, `<!-- unfinished ${svg}`, "x".repeat(200_001), `${svg}${"💡".repeat(50_000)}`]) {
    assert.equal(qrCodeDataUri(value), null);
  }
});
