import test from 'node:test';
import assert from 'node:assert/strict';
import { validateDiscordSyncConfiguration, discordRoleClient, validateDiscordRoleBoundary, reconcileDiscordMember, scheduledDiscordRoleSync } from '../lib/discord-role-sync.js';
const guild='111111111111111111',bot='222222222222222222',owner='333333333333333333',user='444444444444444444',oldRole='555555555555555555',newRole='666666666666666666',protectedRole='777777777777777777',botRole='888888888888888888',cosmetic='999999999999999999';
const config={guildId:guild,botUserId:bot,protectedRoleIds:[protectedRole],runId:'00000000-0000-4000-8000-000000000001'};
function fixture({roles=[oldRole,cosmetic],desired=newRole,change,putError,deleteError}={}) {
 const state={desiredRoleId:desired,managedRoleIds:[oldRole,newRole]}, calls=[],events=[],actual=new Set(roles);
 const guildRoles=[{id:guild,name:'@everyone',position:0,permissions:'1024'},{id:botRole,name:'Sync bot',position:5,permissions:String(1n<<28n)},{id:protectedRole,name:'Ownership',position:10,permissions:'0'},...[oldRole,newRole].map((id,i)=>({id,name:'Staff label',position:i+1,permissions:'0'}))];
 const client=async(method,path)=>{calls.push([method,path]);if(path==='/users/@me')return{id:bot,bot:true};if(path===`/guilds/${guild}`)return{owner_id:owner};if(path.endsWith('/roles')&&method==='GET')return guildRoles;if(path===`/guilds/${guild}/members/${bot}`)return{roles:[botRole]};if(method==='GET')return{roles:[...actual],user:{bot:false}};
  const role=path.split('/').at(-1);if(method==='PUT'){actual.add(role);change?.(state);if(putError)throw putError;}if(method==='DELETE'){if(deleteError)throw deleteError;actual.delete(role);}return true;};
 const run=async()=>reconcileDiscordMember({client,config,boundary:await validateDiscordRoleBoundary(client,config),discordUserId:user,snapshot:async()=>structuredClone(state),record:async(...args)=>events.push(args)});
 return{state,calls,events,actual,guildRoles,client,run};
}
test('reconciliation removes retired managed roles before adding the current rank and never touches cosmetic roles',async()=>{const f=fixture();await f.run();assert.deepEqual(f.calls.filter(([m])=>m!=='GET').map(([m,p])=>[m,p.split('/').at(-1)]),[['DELETE',oldRole],['PUT',newRole]]);assert.deepEqual([...f.actual].sort(),[cosmetic,newRole].sort());const count=f.calls.length;await f.run();assert.equal(f.calls.slice(count).filter(([m])=>m!=='GET').length,0);});
test('suspended/revoked/unlinked and removed mapping states remove all managed roles without granting',async()=>{const f=fixture({desired:null});await f.run();assert.deepEqual([...f.actual],[cosmetic]);assert.equal(f.calls.some(([m])=>m==='PUT'),false);});
test('revocation during a pending grant wins through immediate compensating removal',async()=>{const f=fixture({roles:[cosmetic],change:s=>s.desiredRoleId=null});await assert.rejects(f.run(),e=>e.code==='retry');assert.deepEqual([...f.actual],[cosmetic]);assert.deepEqual(f.calls.filter(([m])=>m!=='GET').map(([m])=>m),['PUT','DELETE']);});
test('ambiguous grant is removed and cleanup rate limit propagates instead of issuing more requests',async()=>{const f=fixture({roles:[],putError:Object.assign(new Error('timeout'),{code:'retry'}),deleteError:Object.assign(new Error('limited'),{code:'rate_limited',retrySeconds:42})});await assert.rejects(f.run(),e=>e.code==='rate_limited'&&e.retrySeconds===42);assert.equal(f.calls.filter(([m])=>m==='PUT').length,1);});
test('exact mapping allowlist rejects a desired role outside its managed set',async()=>{const f=fixture({desired:cosmetic});await assert.rejects(f.run(),e=>e.code==='configuration_error');assert.equal(f.calls.some(([m])=>m!=='GET'),false);});
test('mapped roles with any guild power, integrations, ownership, or excessive hierarchy are rejected',async()=>{for(const tweak of [{permissions:String(1n<<40n)},{permissions:String(1n<<13n)},{managed:true},{position:5},{name:'Ownership'}]){const f=fixture({roles:[]});Object.assign(f.guildRoles.find(r=>r.id===newRole),tweak);await assert.rejects(f.run(),e=>e.code==='configuration_error');assert.equal(f.calls.some(([m])=>m==='PUT'),false);}});
test('bot rejects admin/moderation/unknown permissions and must stay below all protected roles',async()=>{for(const bit of [3n,13n,17n,24n,40n,51n,52n,60n]){const f=fixture();f.guildRoles.find(r=>r.id===botRole).permissions=String((1n<<28n)|(1n<<bit));await assert.rejects(validateDiscordRoleBoundary(f.client,config),e=>e.code==='configuration_error');}const f=fixture();f.guildRoles.find(r=>r.id===protectedRole).position=4;await assert.rejects(validateDiscordRoleBoundary(f.client,config),e=>e.code==='configuration_error');});
test('Discord client fixes the origin, blocks redirects and preserves fractional Retry-After without exposing provider bodies',async()=>{let request;const client=discordRoleClient('test-bot-token',{fetchImpl:async(url,options)=>{request={url,options};return new Response(JSON.stringify({retry_after:2.5,message:'provider-private-body'}),{status:429});}});await assert.rejects(client('PUT',`/guilds/${guild}/members/${user}/roles/${newRole}`),e=>e.code==='rate_limited'&&e.retrySeconds===3&&!e.message.includes('private'));assert.equal(request.options.redirect,'error');assert.equal(request.options.credentials,'omit');assert.equal(request.url,`https://discord.com/api/v10/guilds/${guild}/members/${user}/roles/${newRole}`);await assert.rejects(client('POST','https://evil.example'),e=>e.code==='configuration_error');});
const request=(body={})=>({method:'POST',body,headers:{'content-type':'application/json',authorization:'Bearer '+'a'.repeat(64)}});
test('disabled worker has zero provider/database IO and rejects caller-supplied targets',async()=>{let calls=0;const deps={env:{DISCORD_ROLE_SYNC_ENABLED:'false'},callRpc:async()=>calls++,fetchImpl:async()=>calls++};assert.equal((await scheduledDiscordRoleSync(request(),deps)).reason,'disabled');assert.equal(calls,0);await assert.rejects(scheduledDiscordRoleSync(request({member:user}),deps),e=>e.status===400);});
test('worker persists429 backoff and stops the whole batch without returning identities or credentials',async()=>{const calls=[];const result=await scheduledDiscordRoleSync(request(),{env:{DISCORD_ROLE_SYNC_ENABLED:'true',DISCORD_ROLE_SYNC_BOT_TOKEN:'test-token'},callRpc:async(name,args)=>{calls.push([name,args]);if(name==='service_claim_discord_role_sync')return config;if(name==='service_read_discord_role_sync')return[user,owner];},fetchImpl:async()=>new Response(JSON.stringify({retry_after:23}),{status:429})});assert.deepEqual(result.summary,{checked:0,failed:1,deferred:1});assert.equal(calls.at(-1)[1].p_event,'rate_limited');assert.equal(calls.at(-1)[1].p_retry_seconds,23);assert.ok(!JSON.stringify(result).includes(user));});

test('revocation removes a previously safe managed role even after dangerous permissions are added',async()=>{const f=fixture({desired:null});f.guildRoles.find(r=>r.id===oldRole).permissions=String(1n<<40n);await f.run();assert.equal(f.actual.has(oldRole),false);assert.equal(f.calls.some(([m])=>m==='PUT'),false);});

test('deployed and local routes reach the guarded worker without authentication or a new function',async()=>{
 const {readFileSync}=await import('node:fs');const {default:router}=await import('../api/router.js');
 const vercel=JSON.parse(readFileSync(new URL('../vercel.json',import.meta.url),'utf8'));
 for(const route of ['internal/discord-role-sync','admin/discord-role-sync'])assert.ok(vercel.rewrites.some(r=>r.source==='/api/'+route&&r.destination==='/api/router?_route='+route));
 const local=readFileSync(new URL('../dev-server.mjs',import.meta.url),'utf8');assert.match(local,/POST \/api\/internal\/discord-role-sync/);assert.match(local,/GET \/api\/admin\/discord-role-sync/);
 let payload,status;const headers={};const res={setHeader:(key,value)=>headers[key.toLowerCase()]=value,end:body=>payload=JSON.parse(body),set statusCode(value){status=value},get statusCode(){return status}};
 await router({method:'POST',url:'/api/router?_route=internal/discord-role-sync',headers:{'content-type':'application/json'},body:{}},res);assert.equal(status,401);assert.match(headers['cache-control'],/no-store/);assert.ok(!JSON.stringify(payload).includes('discord_user_id'));
 await router({method:'GET',url:'/api/router?_route=admin/discord-role-sync',headers:{}},res);assert.equal(status,401);
 await router({method:'POST',url:'/api/router?_route=admin/discord-role-sync',headers:{origin:'https://evil.example',host:'www.browserp.com','content-type':'application/json'},body:{}},res);assert.equal(status,403);
});

test('owner configuration rejects rounded numeric IDs and accepts only exact strings',()=>{const valid={guildId:guild,botUserId:bot,protectedRoleIds:[protectedRole],mappings:{moderator:newRole},enabled:false,revokeOnly:false,expectedVersion:0};assert.doesNotThrow(()=>validateDiscordSyncConfiguration(valid));for(const change of [{guildId:Number(guild)},{botUserId:Number(bot)},{protectedRoleIds:[Number(protectedRole)]},{mappings:{moderator:Number(newRole)}},{protectedRoleIds:null},{mappings:{owner:newRole}}])assert.throws(()=>validateDiscordSyncConfiguration({...valid,...change}),e=>e.status===400);});
