import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {JSDOM} from "jsdom";
const source=readFileSync(new URL("../public/staffpanel-v3.js",import.meta.url),"utf8");
const instrumented=source.replace(/\n  init\(\);\n\}\)\(\);\s*$/,"\n  window.__reviewTest={openReview};\n})();");
const settle=async()=>{for(let i=0;i<5;i++)await new Promise(resolve=>setImmediate(resolve));};
const id="bbbbbbbb-0000-4000-8000-000000000001";
function fixture(t){const dom=new JSDOM('<p id="staff-status-v3"></p>',{url:"https://browserp.test/staffpanel/moderation",runScripts:"outside-only"});const w=dom.window;t.after(()=>w.close());w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};const calls=[];let version=3;
 w.fetch=async(path,options={})=>{calls.push({path,options,body:options.body&&JSON.parse(options.body)});const read=path.startsWith("/api/admin/item");return{ok:read,status:read?200:409,json:async()=>read?{item:{id,name:"Fixture listing",reviewVersion:version++,queueVersion:7,history:[{name:"Original name",description:"Earlier description",reviewNote:"Correct the link",recordedAt:"2026-09-05T10:00:00Z"}]}}:{error:"The submission changed. Read its latest details."}};};w.eval(instrumented);return{w,doc:w.document,calls,open:()=>w.__reviewTest.openReview({id,kind:"listing"})};}
function decide(h){const form=h.doc.querySelector("dialog form");form.elements.reason.value="A clear decision reason";form.dispatchEvent(new h.w.Event("submit",{bubbles:true,cancelable:true}));}
test("staff decisions use versions actually read in the dialog and conflicts require loading latest evidence",async t=>{const h=fixture(t);const pending=h.open();await settle();assert.match(h.doc.querySelector("dialog").textContent,/Previous submission details.*Original name/s);decide(h);await settle();const first=h.calls.find(c=>c.options.method==="POST");assert.equal(first.body.expectedVersion,3);assert.equal(first.body.expectedQueueVersion,7);assert.match(h.doc.querySelector("dialog").textContent,/Submission changed/);const refresh=h.doc.querySelector("dialog form");refresh.dispatchEvent(new h.w.Event("submit",{bubbles:true,cancelable:true}));await settle();assert.equal(h.calls.filter(c=>c.path.startsWith("/api/admin/item")).length,2);assert.match(h.doc.querySelector("dialog").textContent,/Review listing/);const cancel=[...h.doc.querySelectorAll("dialog button")].find(x=>x.textContent==="Cancel");cancel.click();await pending;assert.equal(h.calls.filter(c=>c.options.method==="POST").length,1);});

test("legacy review dialog waits for current evidence, forwards both versions and blocks stale decisions",async t=>{
 const legacy=readFileSync(new URL("../public/browserp-portal-v2.js",import.meta.url),"utf8").replace(/\n  init\(\);\n\}\)\(\);\s*$/,"\n  state.csrfToken='fixture'; window.__reviewTest={openReview,wireReviewDialog};\n})();");
 const dom=new JSDOM('<dialog id="review-dialog"><h2 id="review-dialog-title"></h2><form id="review-form"><div id="review-evidence"></div><label><textarea id="review-reason" required></textarea></label><div id="review-actions"></div><p id="review-status"></p></form></dialog>',{url:"https://browserp.test/staff",runScripts:"outside-only"});const w=dom.window;t.after(()=>w.close());w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};let finish;const calls=[];
 w.fetch=async(path,options={})=>{calls.push({path,options,body:options.body&&JSON.parse(options.body)});if(path.startsWith("/api/admin/item"))return new Promise(resolve=>{finish=()=>resolve({ok:true,json:async()=>({item:{id,reviewVersion:8,queueVersion:10,name:"Current listing"}})});});return{ok:false,status:409,json:async()=>({error:"Submission changed"})};};
 w.eval(legacy);w.__reviewTest.wireReviewDialog();const opening=w.__reviewTest.openReview("listing",id,"Review listing",[["approved","Approve",""]]);await settle();const submit=w.document.querySelector("[data-review-action]");assert.equal(submit.disabled,true);finish();await opening;assert.equal(submit.disabled,false);w.document.querySelector("#review-reason").value="Reviewed current evidence";w.document.querySelector("#review-form").dispatchEvent(new w.SubmitEvent("submit",{bubbles:true,cancelable:true,submitter:submit}));await settle();const saved=calls.find(c=>c.options.method==="POST");assert.ok(saved,JSON.stringify({calls,status:w.document.querySelector("#review-status").textContent}));assert.equal(saved.body.expectedVersion,8);assert.equal(saved.body.expectedQueueVersion,10);assert.equal(submit.disabled,true);assert.match(w.document.querySelector("#review-status").textContent,/open it again to read/);
});
